name = "admin-connector"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "connectors"
database_name = "connectors-db"
database_id = "48afca59-3715-40f3-ab53-a00f428296a7"

[[kv_namespaces]]
binding = "ADMIN_CACHE"
id = "905b848b52ba4bf69fe1d59fbfe29d84"

[[services]]
binding = "AUTH_SERVICE"
service = "auth-worker"

[[services]]
binding = "PAYMENT_SERVICE"
service = "payment-worker"

[[services]]
binding = "WALLET_SERVICE"
service = "wallet-worker"

[[services]]
binding = "PAYOUT_SERVICE"
service = "payout-worker"

[[services]]
binding = "DISPUTE_SERVICE"
service = "dispute-worker"

[[services]]
binding = "NOTIFICATION_SERVICE"
service = "notification-worker"

[[services]]
binding = "EVENT_BUS"
service = "event-bus-worker"